import Head from 'next/head';
import ListingLayout from '@/layouts/ListingLayout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListingLayout>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet nemo ut
        quisquam iure pariatur reiciendis, itaque architecto eum natus debitis
        voluptatem ipsam maxime praesentium omnis accusamus blanditiis odio
        modi. Sequi, facere tempore. Numquam, omnis. Cum soluta alias distinctio
        ipsum eum quibusdam eligendi nisi impedit illo fuga natus aliquam,
        molestias deleniti sapiente quas vel, non molestiae commodi laudantium
        eveniet autem unde rerum libero tempora? Incidunt vel unde in harum
        eveniet maxime optio voluptatibus ipsam, similique ab assumenda
        obcaecati officiis sit odio modi perspiciatis quo exercitationem
        repellat dolore. Praesentium sed tempora facere temporibus ullam sequi a
        quo, qui doloribus similique nulla mollitia.
      </ListingLayout>
    </>
  );
}
