export type TUploadResponse = {
  apiKey: string;
  assetId: string;
  bytes: number;
  createdAt: string;
  etag: string;
  folder: string;
  format: string;
  height: number;
  originalFilename: string;
  placeholder: boolean;
  publicId: string;
  resourceType: string;
  secureUrl: string;
  signature: string;
  tags: [];
  type: string;
  url: string;
  version: number;
  versionId: string;
  width: number;
};
